package Array_Prog;

public class Exception {
	public static void main(String[] args) {
		//1
		try {

		} finally {
			// TODO: handle finally clause
		}

		//2
		try {

		} catch (Exception e) {
			// TODO: handle exception
		}
		finally {

		}

		//3
		catch (Exception e) {
			// TODO: handle exception
		}

		//4
		finally {

		}

		//5
		catch (Exception e) {
			// TODO: handle exception
		}finally {

		}

		//6
		try {

		} 
		System.out.println("hello");
		finally {

		}

		//7
		try {

		} catch (Exception e) {
			// TODO: handle exception
		}
		System.out.println("hi");
		finally {

		}

		//8
		try {

		} catch (Exception e) {
			// TODO: handle exception
		}catch (Exception e) {
			// TODO: handle exception
		}

		//9
		try{

		}try{

		}catch (Exception e) {
			// TODO: handle exception
		}

		//10
		try{
			try {

			} catch (Exception e) {
				// TODO: handle exception
			}
		}
		catch (Exception e) {
			// TODO: handle exception
		}

		//11
		try {

		} finally {
			// TODO: handle finally clause
			try {

			} finally {
				// TODO: handle finally clause
			}
		}
	}
}
